[package]
name = "neuron-runtime"
version.workspace = true
edition.workspace = true

[features]
default = ["native"]
native = ["rayon", "libloading"]

[dependencies]
neuron-compiler = { path = "../compiler" }
rayon = { version = "1.8", optional = true }
matrixmultiply = "0.3"
libloading = { version = "0.8", optional = true }
serde_json = "1.0"
num-bigint = "0.5.1"
num-traits = "0.2.19"

[dev-dependencies]



